name: math_engine
description: A simple math engine.
version: 1.0.0
repository: https://github.com/zTomz/Flutter-Sample-Projects/tree/main/Calculator/math_engine

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
